make db setup scripts fail if not invoked from correct dir

diff --git a/scripts/mysqltables b/scripts/mysqltables
--- a/scripts/mysqltables
+++ b/scripts/mysqltables
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-test -f config.ini.php5 || cd ${HOME}/intranet2
+test -f config.ini.php5 || (echo "Config not found" && exit 1)
 
 echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
 echo "!!!!!         Warning!         !!!!!"
